### ISSUE TITLE
Different color for event types

### ISSUE THREAD

**Issue by abdulkadhir** [Bhavana1622/ionic2-calendar-event#1]
hi @Bhavana1622 i want to differentiate  event types based on color 

 ` [
        {
            "id": 5,
            "title": "easter",
            "description": "easter",
            "start": "19/04/18  00:00 AM",
            "end": "19/04/18  00:00 AM",
            "event_type": "Holidays",
            "allDay": false
        },
        {
            "id": 7,
            "title": "Annual Day Celebrations",
            "description": "Celebrating Time",
            "start": "26/04/18  20:00 PM",
            "end": "26/04/18  23:00 PM",
            "event_type": "School Celebration",
            "allDay": false
        },
`

i want different colors for different event_type 
i tried your code but it is not working

**Comment by Bhavana1622** [comment]
Hi @abdulkadhir. 
If you notice, in my code the attribute that's giving the colour to the calendar date is "eventcolor" which holds CSS colours as it's values (green ,red).  However in your code there is no such attribute that can be assigned to CSS colours. For example if you need a separate Colour for event_type HOLIDAYS then you can add an attribute say event_colour: and assign CSS colour  "red" to it.. then you can use the code the way I have and have separate Colours for different event types. 

I hope it helps
